import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Upload, Download, Copy, Trash2, Search, Filter } from "lucide-react";
import { useScenariosStore } from "../../store/scenarios";
import { Scenario } from "../../types/core";
import { exportScenarios, importJsonFile, validateFileType, validateFileSize } from "../../utils/export";
import { useToast } from "@/hooks/use-toast";

export default function ScenariosPage() {
  const {
    scenarios,
    selectedIds,
    addScenario,
    updateScenario,
    deleteScenarios,
    duplicateScenario,
    setSelectedIds,
    toggleSelected,
    selectAll,
    clearSelection,
    importScenarios,
    exportScenarios: exportSelected,
    initializeDemoData,
  } = useScenariosStore();

  const { toast } = useToast();
  
  const [searchQuery, setSearchQuery] = useState("");
  const [languageFilter, setLanguageFilter] = useState<string>("all");
  const [crisisFilter, setCrisisFilter] = useState<string>("all");
  const [editingScenario, setEditingScenario] = useState<Scenario | null>(null);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isNewScenario, setIsNewScenario] = useState(false);

  const filteredScenarios = useMemo(() => {
    return scenarios.filter(scenario => {
      const matchesSearch = scenario.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                           scenario.topic.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesLanguage = languageFilter === "all" || scenario.language === languageFilter;
      const matchesCrisis = crisisFilter === "all" || scenario.crisis_signals === crisisFilter;
      
      return matchesSearch && matchesLanguage && matchesCrisis;
    });
  }, [scenarios, searchQuery, languageFilter, crisisFilter]);

  const handleNewScenario = () => {
    const newScenario: Scenario = {
      id: "", // Will be generated by store
      name: "New Scenario",
      language: "es",
      topic: "relationship",
      attachment_style: "secure",
      emotional_intensity: 0.5,
      cognitive_noise: 0.2,
      crisis_signals: "none",
      goals: ["plan"],
      seed_turns: ["Tell me what's happening..."],
      success_criteria: {
        must: ["Provide helpful response"],
        nice_to_have: ["Show empathy"],
      },
    };
    
    setEditingScenario(newScenario);
    setIsNewScenario(true);
    setIsEditDialogOpen(true);
  };

  const handleEditScenario = (scenario: Scenario) => {
    setEditingScenario({ ...scenario });
    setIsNewScenario(false);
    setIsEditDialogOpen(true);
  };

  const handleSaveScenario = () => {
    if (!editingScenario) return;

    if (isNewScenario) {
      addScenario(editingScenario);
      toast({ title: "Scenario created", description: "New scenario has been added" });
    } else {
      updateScenario(editingScenario.id, editingScenario);
      toast({ title: "Scenario updated", description: "Scenario has been saved" });
    }

    setIsEditDialogOpen(false);
    setEditingScenario(null);
  };

  const handleImport = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (!validateFileType(file)) {
      toast({
        title: "Invalid file type",
        description: "Please select a JSON file",
        variant: "destructive",
      });
      return;
    }

    if (!validateFileSize(file)) {
      toast({
        title: "File too large",
        description: "File size must be under 10MB",
        variant: "destructive",
      });
      return;
    }

    try {
      const data = await importJsonFile(file);
      const result = importScenarios(Array.isArray(data) ? data : [data]);
      
      toast({
        title: "Import completed",
        description: `${result.success} scenarios imported successfully${result.errors.length > 0 ? ` (${result.errors.length} errors)` : ''}`,
      });
      
      if (result.errors.length > 0) {
        console.error("Import errors:", result.errors);
      }
    } catch (error) {
      toast({
        title: "Import failed",
        description: "Failed to import scenarios",
        variant: "destructive",
      });
    }
    
    // Reset input
    event.target.value = "";
  };

  const handleExport = () => {
    const scenariosToExport = exportSelected(selectedIds);
    exportScenarios(scenariosToExport);
    toast({
      title: "Export completed",
      description: `${scenariosToExport.length} scenarios exported`,
    });
  };

  const handleDelete = () => {
    if (selectedIds.length === 0) return;
    
    deleteScenarios(selectedIds);
    toast({
      title: "Scenarios deleted",
      description: `${selectedIds.length} scenarios removed`,
    });
  };

  if (scenarios.length === 0) {
    return (
      <div className="max-w-7xl mx-auto">
        <div className="text-center py-12">
          <h1 className="text-3xl font-bold mb-4">No Scenarios</h1>
          <p className="text-muted-foreground mb-6">
            Get started by creating your first scenario or loading demo data.
          </p>
          <div className="flex gap-2 justify-center">
            <Button onClick={initializeDemoData}>
              Load Demo Scenarios
            </Button>
            <Button variant="outline" onClick={handleNewScenario}>
              <Plus className="mr-2 h-4 w-4" />
              Create First Scenario
            </Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Scenarios</h1>
          <p className="text-muted-foreground">Manage test scenarios for Nini evaluation</p>
        </div>
        
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleNewScenario}>
            <Plus className="mr-2 h-4 w-4" />
            New
          </Button>
          
          <div className="relative">
            <input
              type="file"
              accept=".json"
              onChange={handleImport}
              className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
            />
            <Button variant="outline">
              <Upload className="mr-2 h-4 w-4" />
              Import
            </Button>
          </div>
          
          <Button variant="outline" onClick={handleExport} disabled={selectedIds.length === 0}>
            <Download className="mr-2 h-4 w-4" />
            Export ({selectedIds.length})
          </Button>
          
          <Button variant="outline" onClick={handleDelete} disabled={selectedIds.length === 0}>
            <Trash2 className="mr-2 h-4 w-4" />
            Delete ({selectedIds.length})
          </Button>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex gap-4 items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search scenarios..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
            
            <Select value={languageFilter} onValueChange={setLanguageFilter}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Languages</SelectItem>
                <SelectItem value="es">Spanish</SelectItem>
                <SelectItem value="en">English</SelectItem>
                <SelectItem value="mix">Mixed</SelectItem>
              </SelectContent>
            </Select>
            
            <Select value={crisisFilter} onValueChange={setCrisisFilter}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Crisis Types</SelectItem>
                <SelectItem value="none">No Crisis</SelectItem>
                <SelectItem value="ambiguous">Ambiguous</SelectItem>
                <SelectItem value="clear">Clear Crisis</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Scenarios Table */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Scenarios ({filteredScenarios.length})</CardTitle>
            <div className="flex items-center gap-2">
              <Checkbox
                checked={selectedIds.length === filteredScenarios.length && filteredScenarios.length > 0}
                onCheckedChange={(checked) => {
                  if (checked) {
                    selectAll();
                  } else {
                    clearSelection();
                  }
                }}
              />
              <span className="text-sm text-muted-foreground">Select All</span>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-12"></TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Language</TableHead>
                <TableHead>Topic</TableHead>
                <TableHead>Crisis</TableHead>
                <TableHead>Attachment</TableHead>
                <TableHead>Goals</TableHead>
                <TableHead className="w-24">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredScenarios.map((scenario) => (
                <TableRow key={scenario.id}>
                  <TableCell>
                    <Checkbox
                      checked={selectedIds.includes(scenario.id)}
                      onCheckedChange={() => toggleSelected(scenario.id)}
                    />
                  </TableCell>
                  <TableCell className="font-medium">{scenario.name}</TableCell>
                  <TableCell>
                    <Badge variant="outline">{scenario.language}</Badge>
                  </TableCell>
                  <TableCell>{scenario.topic}</TableCell>
                  <TableCell>
                    <Badge 
                      variant={
                        scenario.crisis_signals === 'clear' ? 'destructive' :
                        scenario.crisis_signals === 'ambiguous' ? 'secondary' :
                        'outline'
                      }
                    >
                      {scenario.crisis_signals}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">{scenario.attachment_style}</Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-1 flex-wrap">
                      {scenario.goals.slice(0, 2).map((goal, index) => (
                        <Badge key={index} variant="secondary" className="text-xs">
                          {goal}
                        </Badge>
                      ))}
                      {scenario.goals.length > 2 && (
                        <Badge variant="secondary" className="text-xs">
                          +{scenario.goals.length - 2}
                        </Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleEditScenario(scenario)}
                      >
                        Edit
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => duplicateScenario(scenario.id)}
                      >
                        <Copy className="h-3 w-3" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {isNewScenario ? 'Create New Scenario' : 'Edit Scenario'}
            </DialogTitle>
          </DialogHeader>
          
          {editingScenario && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input
                    id="name"
                    value={editingScenario.name}
                    onChange={(e) => setEditingScenario({
                      ...editingScenario,
                      name: e.target.value
                    })}
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="topic">Topic</Label>
                  <Input
                    id="topic"
                    value={editingScenario.topic}
                    onChange={(e) => setEditingScenario({
                      ...editingScenario,
                      topic: e.target.value
                    })}
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>Language</Label>
                  <Select
                    value={editingScenario.language}
                    onValueChange={(value: any) => setEditingScenario({
                      ...editingScenario,
                      language: value
                    })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="es">Spanish</SelectItem>
                      <SelectItem value="en">English</SelectItem>
                      <SelectItem value="mix">Mixed</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Attachment Style</Label>
                  <Select
                    value={editingScenario.attachment_style}
                    onValueChange={(value: any) => setEditingScenario({
                      ...editingScenario,
                      attachment_style: value
                    })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="anxious">Anxious</SelectItem>
                      <SelectItem value="avoidant">Avoidant</SelectItem>
                      <SelectItem value="secure">Secure</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Crisis Signals</Label>
                  <Select
                    value={editingScenario.crisis_signals}
                    onValueChange={(value: any) => setEditingScenario({
                      ...editingScenario,
                      crisis_signals: value
                    })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">None</SelectItem>
                      <SelectItem value="ambiguous">Ambiguous</SelectItem>
                      <SelectItem value="clear">Clear</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="goals">Goals (comma-separated)</Label>
                <Input
                  id="goals"
                  value={editingScenario.goals.join(", ")}
                  onChange={(e) => setEditingScenario({
                    ...editingScenario,
                    goals: e.target.value.split(",").map(g => g.trim()).filter(Boolean)
                  })}
                  placeholder="plan, validation, insight"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="seed-turns">Seed Turns</Label>
                <Textarea
                  id="seed-turns"
                  value={editingScenario.seed_turns.join("\n")}
                  onChange={(e) => setEditingScenario({
                    ...editingScenario,
                    seed_turns: e.target.value.split("\n").filter(Boolean)
                  })}
                  className="min-h-[100px]"
                  placeholder="Enter each seed turn on a new line"
                />
              </div>

              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleSaveScenario}>
                  {isNewScenario ? 'Create' : 'Save'}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}